import React from 'react'
import "./Started.css"
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import cvimg from "../../assets/cv-img.png"
import { Link } from 'react-router-dom';
import Cvmaker from '../Cvmaker/Cvmaker';
import { Button } from '@mui/material';
const Started = () => {
    return (
        <>
        <div className="started">
            <div className="started-text">
                <h1 className="h1">IMPRESSIVE RESUMES</h1>
                <h1 className="h1-second" >EASY ONLINE BUILDER</h1>
                <p><CheckCircleIcon className='icon' /> Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.</p>
                <p><CheckCircleIcon className='icon' /> Effortless crafting. Real-time preview & pre-written <span className="span">resume examples.
                    Dozens of HR-approved resume templates.</span></p>
                <p><CheckCircleIcon className='icon' /> Land your dream job with the perfect resume employers are looking for!</p>
           <Link to="/cvmaker" ><button className="started-btn" >Get Started</button></Link>
            </div>
<div className="started-img" >
<img className="cv-img" src={cvimg} alt="" />
</div>
        </div>
        </>
    )
}

export default Started
